# Generated by Django 6.0.2 on 2026-03-20 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('university', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('company', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('responsibilities', models.TextField()),
                ('ai_content', models.TextField(blank=True, null=True)),
                ('skills', models.TextField()),
                ('ref1_name', models.CharField(blank=True, max_length=255)),
                ('ref1_job', models.CharField(blank=True, max_length=255)),
                ('ref1_contact', models.CharField(blank=True, max_length=255)),
                ('ref2_name', models.CharField(blank=True, max_length=255)),
                ('ref2_job', models.CharField(blank=True, max_length=255)),
                ('ref2_contact', models.CharField(blank=True, max_length=255)),
                ('is_paid', models.BooleanField(default=False)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
