# Generated by Django 6.0.2 on 2026-03-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuroCV', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='ai_content',
            new_name='ai_bullets',
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
