# Generated by Django 6.0.2 on 2026-03-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neuroCV', '0002_alter_resume_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='ai_bullets',
            new_name='ai_bullet',
        ),
    ]
